services:
  app:
    build: .
    container_name: rag_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_ACCESS_TOKEN}
    depends_on:
      - mongo
      - qdrant
      - clearml

  mongo:
    image: mongo:latest
    container_name: "rag_system_mongo"
    logging:
      options:
        max-size: 1g
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "rag_systen_qdrant"
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local
    restart: always
  
  clearml:
    image: allegroai/clearml
    container_name: rag_system_clearml
    ports:
      - "8080:8080"
      - "8008:8008"

volumes:
  mongo_data:
  qdrant_data:

networks:
  local:
    driver: bridge